### PR TITLE
Inclusion of other catalogs + bug fix

### PR DESCRIPTION
**Pull request by tnorth**
Hello,

The script now generates files for catalogs ohara, hikari, and hoya. Generated files are identical to the files generated with the old version of the script.

Warning: the sumita catalog was not included.
It seems that the old script is not able to generate it. Moreover, if fixed the output is quite different from what was expected (see below). Looks like the coefficients have to be double-checked.

Thanks,

Example:

``` diff
--- output_ref/sumita/K-BaF8.yml    2015-11-26 08:55:34.000000000 +0100
+++ output/sumita/K-BaF8.yml    2016-02-08 10:15:47.570142474 +0100
@@ -1,10 +1,45 @@
-# This file is part of refractiveindex.info database
-# refractiveindex.info database is subject to the terms of the GNU Lesser General Public License (LGPL) v.3
-# If a copy of the LGPL was not distributed with this file, you can obtain one at http://www.gnu.org/licenses/lgpl
-
-REFERENCES: "<a href=\"http://www.sumita-opt.co.jp/en/catalog.htm\">Sumita Optical Glass Data Book</a>"
-COMMENTS: "Refractive index is relative to air at standard conditions; Wavelength in dispersion formula is as measured in air and expressed in micrometers"
-DATA:
-  - type: formula 3
-    range: 0.365 1.548
-    coefficients: 2.5812079 -1.046647E-2 2 2.0144839E-2 -2 -1.4331954E-4 -4 7.9149799E-5 -6 -2.1453499E-6 -8
+# this file is part of refractiveindex.info database
+# refractiveindex.info database is in the public domain
+# copyright and related rights waived via CC0 1.0
+
+REFERENCES: "<a href="http://www.sumita-opt.co.jp/en/catalog.htm">Sumita Optical Glass Data Book</a>"
+DATA:
+  - type: formula 3 
+    range: 0.36 1.55
+    coefficients: 2.5830562 -0.01131971 2 0.018817464 4 0.00027063309 -2 2.1527561e-05 -4 7.7761941e-07 -6
+  - type: tabulated k
+    data: |
+        0.340 8.7776E-06
+        0.350 3.4286E-06
+        0.360 1.5067E-06
+        0.370 7.5430E-07
+        0.380 4.1071E-07
+        0.390 2.4531E-07
+        0.400 1.5658E-07
+        0.420 9.1481E-08
+        0.440 6.3599E-08
+        0.460 5.5324E-08
+        0.480 4.2250E-08
+        0.500 2.3945E-08
+        0.550 1.7542E-08
+        0.600 1.9137E-08
+        0.650 1.5541E-08
+        0.700 1.6736E-08
+        0.800 1.9127E-08
+        1.060 1.6887E-08
+        1.500 4.7842E-08
+        2.000 3.7033E-07
+INFO:
+    n_is_absolute: false
+    λ_is_vacuum: false
+    temperature: 20.0 °C
+    coefficients_of_thermal_dispersion: 7.3e-07 1.78e-08 -2.34e-10 5.81e-07 1.81e-11 0.234
+    n_d: 1.62374
+    V_d: 47.1
+    glass_code: 624471
+    density: 3.02 g/cm<sup>3</sup>
+    coefficient_of_thermal_expansion_1: 6.7e-06 K<sup>-1</sup>
+    coefficient_of_thermal_expansion_2: 9.8e-06 K<sup>-1</sup>
+    ΔP_gF: 0.0001
+    climatic_resistance: 1.0
+    acid_resistance: 2.0
```

### CODE REVIEW

**Comment by polyanskiy** [comment]
Hi Thibault:
1) I think that processing single .agf file at a time makes more sense: in the future we will only need to update glass data when a glass maker releases a new catalog; and they don't do this simultaneously
2) coefficients in line 105 must be [None, 2, -2, -4, -6, -8, -10, -12](note: there is no)
3) sumita catalog was recently updated (the current version is dated 2016/01/13), this is why coefficients in the dispersion formula are slightly different. The new YAML file in your example matches the k-baf8 entry in sumita.agf. So, no problem here.
Could you please fix 1) and 2) before I merge the changes?
Thank you very much again for all you are doing!

**Comment by tnorth** [comment]
Hi Mikhail,

Thanks for the feedback. 
To fix 1), I will rollback the changes and let the user pass the catalog name as argument.

For 2), I haven't checked how the coefficients to be added are generated, but the original sequence is [None, 2, 4, -2, -4, -6, -8, -10, -12]. Is that what you meant? Or is this sequence different for some catalogs?

I will make these fixes and commit ASAP.
Thanks!

**Comment by polyanskiy** [comment]
Hi Thibault,
You are right, the coefficient sequence is correct for formula "13". However, formula "1" is different: [None, 2, -2, -4, -6, -8] - see pp.590-591 in the zemax manual https://physics.ucsd.edu/neurophysics/Manuals/Zemax/ZemaxManual.pdf. The corresponding formulas are "Schott" for "1" and "Extended 3" for "13".
You found one more bug!
Thank you,
Mikhail

**Comment by tnorth** [comment]
Hi Mikhail,
Fixed in 89cf418 . Please double-check :)

**Pull request merged**
